#**Project 2**

##Uplaoding, Cleaning, and Sorting

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**2000**

In [3]:
url = '/content/drive/MyDrive/Project 2/c2000_a.csv'
data00 = pd.read_csv(url)
data00.head()

,unitid,cipcode,awlevel,xcrace01,crace01,xcrace02,crace02,xcrace03,crace03,xcrace04,...,xcrace12,crace12,xcrace13,crace13,xcrace14,crace14,xcrace15,crace15,xcrace16,crace16
0,100636,9.0501,3,Z,0,Z,0,R,3,R,...,R,9,Z,0,R,1,R,14,R,12
1,100636,10.0199,3,Z,0,Z,0,R,19,R,...,R,103,R,14,R,8,R,331,R,129
2,100636,11.0101,3,Z,0,Z,0,R,4,R,...,R,7,R,6,R,1,R,116,R,10
3,100636,13.9999,3,Z,0,Z,0,R,90,R,...,R,113,R,32,R,3,R,826,R,150
4,100636,15.0303,3,Z,0,Z,0,R,83,R,...,R,88,R,46,R,7,R,860,R,102

In [4]:
data00 = data00.rename(columns={'cipcode': 'CIPCODE', 'awlevel': 'AWLEVEL', 'year': 'YEAR'})

In [5]:
data00 = data00[['CIPCODE', 'AWLEVEL']].copy()
data00['YEAR'] = 2000
data00.head()

   CIPCODE  AWLEVEL  YEAR
0   9.0501        3  2000
1  10.0199        3  2000
2  11.0101        3  2000
3  13.9999        3  2000
4  15.0303        3  2000

**2005**

In [6]:
url = '/content/drive/MyDrive/Project 2/c2005_a_rv.csv'
data05 = pd.read_csv(url)
data05.head()

,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCRACE01,CRACE01,XCRACE02,CRACE02,XCRACE03,CRACE03,...,XCRACE20,CRACE20,XCRACE21,CRACE21,XCRACE22,CRACE22,XCRACE23,CRACE23,XCRACE24,CRACE24
0,100636,9.0999,1,3,R,0,R,0,R,3,...,R,1,R,0,R,24,R,0,R,28
1,100636,10.0105,1,3,R,0,R,0,R,27,...,R,9,R,0,R,461,R,53,R,579
2,100636,11.0101,1,3,R,0,R,0,R,2,...,R,1,R,0,R,90,R,4,R,97
3,100636,11.0401,1,3,R,0,R,0,R,108,...,R,29,R,0,R,646,R,81,R,936
4,100636,13.0499,1,3,R,0,R,0,R,17,...,R,0,R,0,R,122,R,4,R,160

In [7]:
data05 = data05[['CIPCODE', 'AWLEVEL']].copy()
data05['YEAR'] = 2005
data05.head()

   CIPCODE  AWLEVEL  YEAR
0   9.0999        3  2005
1  10.0105        3  2005
2  11.0101        3  2005
3  11.0401        3  2005
4  13.0499        3  2005

**2010**

In [8]:
url = '/content/drive/MyDrive/Project 2/c2010_a_rv.csv'
data10 = pd.read_csv(url)
data10.head()

,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCNRALM,CNRALM,XCNRALW,CNRALW,XCRACE03,CRACE03,...,XDVCHSM,DVCHSM,XDVCHSW,DVCHSW,XDVCWHT,DVCWHT,XDVCWHM,DVCWHM,XDVCWHW,DVCWHW
0,100636,9.0999,1,3,R,0,R,0,R,3.0,...,R,0,R,0,R,47,R,31,R,16
1,100636,10.0105,1,3,R,0,R,0,R,43.0,...,R,0,R,0,R,802,R,577,R,225
2,100636,11.0101,1,3,R,0,R,0,R,3.0,...,R,0,R,0,R,57,R,54,R,3
3,100636,11.0401,1,3,R,0,R,0,R,107.0,...,R,0,R,0,R,671,R,554,R,117
4,100636,13.0499,1,3,R,0,R,0,R,32.0,...,R,0,R,0,R,166,R,110,R,56

In [9]:
data10 = data10[['CIPCODE', 'AWLEVEL']].copy()
data10['YEAR'] = 2010
data10.head()

   CIPCODE  AWLEVEL  YEAR
0   9.0999        3  2010
1  10.0105        3  2010
2  11.0101        3  2010
3  11.0401        3  2010
4  13.0499        3  2010

**2015**

In [10]:
url = '/content/drive/MyDrive/Project 2/c2015_a_rv.csv'
data15 = pd.read_csv(url)
data15.head()

,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCTOTALT,CTOTALT,XCTOTALM,CTOTALM,XCTOTALW,CTOTALW,...,XCUNKNM,CUNKNM,XCUNKNW,CUNKNW,XCNRALT,CNRALT,XCNRALM,CNRALM,XCNRALW,CNRALW
0,100654,1.0000,1,5,R,3,R,3,Z,0,...,Z,0,Z,0,Z,0,Z,0,Z,0
1,100654,1.0901,1,5,R,4,Z,0,R,4,...,Z,0,Z,0,Z,0,Z,0,Z,0
2,100654,1.1001,1,5,R,9,R,2,R,7,...,Z,0,Z,0,R,3,R,1,R,2
3,100654,1.1001,1,7,R,7,R,2,R,5,...,Z,0,Z,0,R,1,R,1,Z,0
4,100654,1.1001,1,17,R,2,R,1,R,1,...,Z,0,Z,0,R,1,R,1,Z,0

In [11]:
data15 = data15[['CIPCODE', 'AWLEVEL']].copy()
data15['YEAR'] = 2015
data15.head()

   CIPCODE  AWLEVEL  YEAR
0   1.0000        5  2015
1   1.0901        5  2015
2   1.1001        5  2015
3   1.1001        7  2015
4   1.1001       17  2015

**2020**

In [12]:
url = '/content/drive/MyDrive/Project 2/c2020_a_rv.csv'
data20 = pd.read_csv(url)
data20.head()

,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCTOTALT,CTOTALT,XCTOTALM,CTOTALM,XCTOTALW,CTOTALW,...,XCUNKNM,CUNKNM,XCUNKNW,CUNKNW,XCNRALT,CNRALT,XCNRALM,CNRALM,XCNRALW,CNRALW
0,100654,1.0999,1,5,R,3,Z,0,R,3,...,Z,0,R,1,Z,0,Z,0,Z,0
1,100654,1.1001,1,5,R,7,R,2,R,5,...,Z,0,Z,0,Z,0,Z,0,Z,0
2,100654,1.1001,1,7,R,4,R,0,R,4,...,Z,0,Z,0,R,2,R,0,R,2
3,100654,1.1001,1,17,R,2,R,2,R,0,...,Z,0,Z,0,R,1,R,1,R,0
4,100654,1.9999,1,5,R,6,R,4,R,2,...,R,1,R,0,Z,0,Z,0,Z,0

In [13]:
data20 = data20[['CIPCODE', 'AWLEVEL']].copy()
data20['YEAR'] = 2020
data20.head()

   CIPCODE  AWLEVEL  YEAR
0   1.0999        5  2020
1   1.1001        5  2020
2   1.1001        7  2020
3   1.1001       17  2020
4   1.9999        5  2020

**2024**

In [14]:
url = '/content/drive/MyDrive/Project 2/c2024_a.csv'
data24 = pd.read_csv(url)
data24.head()

,UNITID,CIPCODE,MAJORNUM,AWLEVEL,XCTOTALT,CTOTALT,XCTOTALM,CTOTALM,XCTOTALW,CTOTALW,...,XCUNKNM,CUNKNM,XCUNKNW,CUNKNW,XCNRALT,CNRALT,XCNRALM,CNRALM,XCNRALW,CNRALW
0,100654,1.0999,1,5,R,12,R,2,R,10,...,Z,0,Z,0,Z,0,Z,0,Z,0
1,100654,1.1001,1,5,R,10,R,1,R,9,...,Z,0,Z,0,Z,0,Z,0,Z,0
2,100654,1.1001,1,7,R,7,R,1,R,6,...,Z,0,Z,0,R,2,R,1,R,1
3,100654,1.1001,1,17,R,6,R,3,R,3,...,R,0,R,2,R,3,R,2,R,1
4,100654,1.9999,1,5,R,2,R,1,R,1,...,Z,0,Z,0,Z,0,Z,0,Z,0

In [15]:
data24 = data24[['CIPCODE', 'AWLEVEL']].copy()
data24['YEAR'] = 2024
data24.head()

   CIPCODE  AWLEVEL  YEAR
0   1.0999        5  2024
1   1.1001        5  2024
2   1.1001        7  2024
3   1.1001       17  2024
4   1.9999        5  2024

##Merging Datasets

In [16]:
all_dataframes = [data00, data05, data10, data15, data20, data24]
merged_data = pd.concat(all_dataframes, ignore_index=True)

cip_codes_to_filter = [
    11.0101, 11.0102, 11.0103, 11.0199, 11.0201, 11.0202, 11.0203, 11.0299, 11.0301, 11.0401,
    11.0501, 11.0601, 11.0602, 11.0699, 11.0701, 11.0801, 11.0802, 11.0803, 11.0899, 11.0901,
    11.1001, 11.1002, 11.1003, 11.1004, 11.1099, 11.9999, 14.0101, 14.0201, 14.0301, 14.0401,
    14.0501, 14.0601, 14.0701, 14.0801, 14.0802, 14.0803, 14.0804, 14.0805, 14.0899, 14.0901,
    14.0903, 14.0999, 14.1001, 14.1101, 14.1201, 14.1301, 14.1401, 14.1801, 14.1901, 14.2001,
    14.2101, 14.2201, 14.2301, 14.2401, 14.2501, 14.2701, 14.2801, 14.3101, 14.3201, 14.3301,
    14.3401, 14.3501, 14.3601, 14.3701, 14.3801, 14.3901, 14.9999, 15.0000, 15.0101, 15.0201,
    15.0303, 15.0304, 15.0305, 15.0399, 15.0401, 15.0403, 15.0404, 15.0405, 15.0801, 15.0803,
    15.0805, 15.0899, 15.0901, 15.0903, 15.0999, 15.1001, 15.1102, 15.1103, 15.1199, 15.1201,
    15.1202, 15.1203, 15.1204, 15.1299, 15.1301, 15.1302, 15.1303, 15.1304, 15.1305, 15.1306,
    15.1399, 15.1401, 15.1501, 15.9999
]

merged_data_filtered = merged_data[merged_data['CIPCODE'].isin(cip_codes_to_filter)]
merged_data_filtered = merged_data_filtered[merged_data_filtered['AWLEVEL'] == 5]
display(merged_data_filtered.head())

    CIPCODE  AWLEVEL  YEAR
67  11.0101        5  2000
76  14.0801        5  2000
77  14.1001        5  2000
78  14.1901        5  2000
79  15.0201        5  2000

In [17]:
cipcode_totals = merged_data_filtered['CIPCODE'].value_counts().reset_index()
cipcode_totals.columns = ['CIPCODE', 'Total Count']
display(cipcode_totals.head(100))

    CIPCODE  Total Count
0   11.0101         5103
1   11.0701         4890
2   14.1001         2357
3   14.1901         2199
4   11.0401         1907
..      ...          ...
95  15.0999            3
96  15.1103            3
97  14.0802            2
98  11.0601            2
99  11.0203            2

[100 rows x 2 columns]

**With Added Descriptions**

In [18]:
cip_descriptions_df = pd.read_csv('/content/drive/MyDrive/Project 2/CIPCODES+Major - Sheet1.csv', header=None)
cip_descriptions_df.columns = ['CIPCODE','Description']
display(cip_descriptions_df.head())

   CIPCODE                                 Description
0  11.0101  Computer and Information Sciences, General
1  11.0102        Artificial Intelligence and Robotics
2  11.0103                      Information Technology
3  11.0199    Computer and Information Sciences, Other
4  11.0201    Computer Programming/Programmer, General

**TOTALS**

In [19]:
cipcode_totals_with_description = pd.merge(cipcode_totals, cip_descriptions_df, on='CIPCODE', how='left')
display(cipcode_totals_with_description.head())

   CIPCODE  Total Count                                        Description
0  11.0101         5103         Computer and Information Sciences, General
1  11.0701         4890                                   Computer Science
2  14.1001         2357  Electrical, Electronics and Communications Eng...
3  14.1901         2199                             Mechanical Engineering
4  11.0401         1907                        Information Science/Studies

In [20]:
output_path_cip_totals = '/content/drive/MyDrive/Project 2/cipcode_totals_with_description.csv'
cipcode_totals_with_description.to_csv(output_path_cip_totals, index=False)
print(f"DataFrame saved to {output_path_cip_totals}")

DataFrame saved to /content/drive/MyDrive/Project 2/cipcode_totals_with_description.csv

**Table with all information together**

In [21]:
merged_data_with_descriptions = pd.merge(merged_data_filtered, cipcode_totals_with_description, on='CIPCODE', how='left')
merged_data_with_descriptions = merged_data_with_descriptions[['CIPCODE', 'AWLEVEL', 'YEAR', 'Total Count', 'Description']]
display(merged_data_with_descriptions.head())

,CIPCODE,AWLEVEL,YEAR,Total Count,Description
0,11.0101,5,2000,5103,"Computer and Information Sciences, General"
1,14.0801,5,2000,1635,"Civil Engineering, General"
2,14.1001,5,2000,2357,"Electrical, Electronics and Communications Eng..."
3,14.1901,5,2000,2199,Mechanical Engineering
4,15.0201,5,2000,197,Civil Engineering Technology/Technician

In [22]:
output_path = '/content/drive/MyDrive/Project 2/merged_data_with_descriptions.csv'
merged_data_with_descriptions.to_csv(output_path, index=False)
print(f"DataFrame saved to {output_path}")

DataFrame saved to /content/drive/MyDrive/Project 2/merged_data_with_descriptions.csv

##By State Dataset

**This dataset is from IPEDS, year 2023-2024. The only options aaibale with state were the bulk of the majors, Computer and Information Sciences, Engineering, and Engineering techologies/relating fields.**

In [23]:
url = '/content/drive/MyDrive/Project 2/TrendGenerator-Table-q24-05-05-26 12-47.csv'
data_states = pd.read_csv(url, sep=',', engine='python', skiprows=[0,1], header=0)
data_states.head()

,Unnamed: 0,Total,Computer and Information Sciences and Support Services,Engineering?,Engineering Technologies and Engineering-related Fields
0,Total,"612,353","325,746","195,246","91,361"
1,Alabama,"10,813","3,348","3,533","3,932"
2,Alaska,314,97,118,99
3,Arizona,"17,698","10,552","5,039","2,107"
4,Arkansas,"4,578","2,314",878,"1,386"

In [24]:
data_states = data_states.rename(columns={'Unnamed: 0': 'State', 'Engineering?': 'Engineering'})

In [25]:
data_states.head()

,State,Total,Computer and Information Sciences and Support Services,Engineering,Engineering Technologies and Engineering-related Fields
0,Total,"612,353","325,746","195,246","91,361"
1,Alabama,"10,813","3,348","3,533","3,932"
2,Alaska,314,97,118,99
3,Arizona,"17,698","10,552","5,039","2,107"
4,Arkansas,"4,578","2,314",878,"1,386"

In [26]:
data_states['Total'] = pd.to_numeric(
    data_states['Total'].astype(str).str.replace(',', '', regex=False),
    errors='coerce'
)
data_states['Total'] = data_states['Total'].fillna(0)

In [27]:
numeric_cols_to_convert = [
    'Computer and Information Sciences and Support Services',
    'Engineering',
    'Engineering Technologies and Engineering-related Fields'
]

for col in numeric_cols_to_convert:
    data_states[col] = pd.to_numeric(
        data_states[col].astype(str).str.replace(',', '', regex=False),
        errors='coerce'
    )
    data_states[col] = data_states[col].fillna(0)

In [28]:
data_states.dtypes

State                                                       object
Total                                                      float64
Computer and Information Sciences and Support Services     float64
Engineering                                                float64
Engineering Technologies and Engineering-related Fields    float64
dtype: object

In [29]:
output_path_data_states = '/content/drive/MyDrive/Project 2/data_states.csv'
data_states.to_csv(output_path_data_states, index=False)
print(f"DataFrame saved to {output_path_data_states}")

DataFrame saved to /content/drive/MyDrive/Project 2/data_states.csv

##Graphs

In [30]:
!pip install "vegafusion[embed]>=1.5.0"

Requirement already satisfied: vegafusion>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from vegafusion[embed]>=1.5.0) (2.0.3)
Requirement already satisfied: arro3-core in /usr/local/lib/python3.12/dist-packages (from vegafusion>=1.5.0->vegafusion[embed]>=1.5.0) (0.8.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from vegafusion>=1.5.0->vegafusion[embed]>=1.5.0) (26.1)
Requirement already satisfied: narwhals>=1.42 in /usr/local/lib/python3.12/dist-packages (from vegafusion>=1.5.0->vegafusion[embed]>=1.5.0) (2.20.0)

**Table 1 - Interactive Bar Chart**

In [53]:
import altair as alt
alt.data_transformers.enable("vegafusion")

# Define the custom years for the selection
custom_years = [2000, 2005, 2010, 2015, 2020, 2024]

# Create a slider for the year, allowing selection of all years
year_selector = alt.binding_range(min=min(custom_years),
                                max=max(custom_years),
                                step=5,
                                name='Year:')

select_year = alt.selection_point(name='year_selection', fields=['YEAR'], bind=year_selector, value=2000)

# Create a dropdown menu for Degree Description
description_dropdown = alt.binding_select(options=merged_data_with_descriptions['Description'].unique().tolist(),
                                         name='Degree Description:')
select_description = alt.selection_point(fields=['Description'], bind=description_dropdown)

# Create the bar chart
chart = alt.Chart(merged_data_with_descriptions).mark_bar().encode(
    x=alt.X('Description:N', sort='-y', title='Description'),
    y=alt.Y('Total Count:Q', title='Total Count'),
    tooltip=['YEAR', 'Description', 'Total Count']
).add_params(
    select_year,
    select_description
).transform_filter(
    select_year
).transform_filter(
    select_description
).transform_filter(
    alt.datum['Total Count'] > 200 # Filter for Total Count > 200
).properties(
    title='Total Count by Description for Selected Year (Count > 200)'
).interactive()

chart

!pip install "vl-convert-python>=1.6.0"

Requirement already satisfied: vl-convert-python>=1.6.0 in /usr/local/lib/python3.12/dist-packages (1.9.0.post1)

In [32]:
chart

alt.Chart(...)

**Table 2**

In [52]:
import altair as alt
import pandas as pd

# 1. Aggregate data to count degrees per CIPCODE and Year
#    'merged_data_filtered' contains individual entries for each degree awarded with AWLEVEL == 5
degrees_per_year_cipcode = merged_data_filtered.groupby(['YEAR', 'CIPCODE']).size().reset_index(name='Degrees_Awarded')

# 2. Merge with descriptions to get the 'Description' for each CIPCODE
#    'cip_descriptions_df' is available from previous steps
degrees_growth_data = pd.merge(degrees_per_year_cipcode, cip_descriptions_df, on='CIPCODE', how='left')

# Drop rows where Description might be missing if a CIPCODE from merged_data_filtered wasn't in cip_descriptions_df
degrees_growth_data.dropna(subset=['Description'], inplace=True)

# Calculate total degrees awarded for each description across all years to identify top descriptions
total_degrees_by_description = degrees_growth_data.groupby('Description')['Degrees_Awarded'].sum().reset_index(name='Overall_Total_Degrees')

# Get the top N descriptions based on their overall total degrees
top_n = 15 # You can adjust this number to show more or fewer lines
top_descriptions = total_degrees_by_description.nlargest(top_n, 'Overall_Total_Degrees')['Description'].tolist()

# Filter the data to include only the top descriptions
filtered_degrees_growth_data = degrees_growth_data[degrees_growth_data['Description'].isin(top_descriptions)]

# Create a selection for the descriptions (to act like buttons), allowing multiple selections
legend_selection = alt.selection_point(fields=['Description'], bind='legend', name='description_selection', toggle=True)

# Add an interval selection for the YEAR axis
year_interval_selection = alt.selection_interval(encodings=['x'], name='year_interval')

# Create the line chart
line_chart = alt.Chart(filtered_degrees_growth_data).mark_line(point=True).encode(
    x=alt.X('YEAR:O', axis=alt.Axis(format='d'), title='Year'), # 'O' for ordinal to treat years as discrete categories
    y=alt.Y('Degrees_Awarded:Q', title='Degrees Awarded'),
    color=alt.Color('Description:N', legend=alt.Legend(title="Degree Description")),
    tooltip=['YEAR:O', 'Description:N', 'Degrees_Awarded:Q'],
    opacity=alt.condition(legend_selection, alt.value(1), alt.value(0.2)) # Highlight selected descriptions
).add_params(
    legend_selection,
    year_interval_selection
).transform_filter(
    year_interval_selection # Filter based on the year interval selection
).properties(
    title=f'Growth of Top {top_n} Degrees Over Time (Select Year Range)'
).interactive() # Allows zooming and panning

line_chart

alt.Chart(...)

**Table 3**

In [40]:
import pandas as pd
import plotly.express as px

data_states_cleaned = data_states.copy()

data_states_cleaned = data_states_cleaned[
    data_states_cleaned['State'] != 'Total'
]

data_states_cleaned = data_states_cleaned.dropna(subset=['State'])

data_states_cleaned['State'] = (
    data_states_cleaned['State']
    .astype(str)
    .str.strip()
)


state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY'
}

data_states_cleaned['abbr'] = (
    data_states_cleaned['State']
    .map(state_abbrev)
)

data_states_cleaned = data_states_cleaned.dropna(subset=['abbr'])


selected_column = (
    'Computer and Information Sciences and Support Services'
)

fig = px.choropleth(
    data_states_cleaned,
    locations='abbr',
    locationmode='USA-states',
    color=selected_column,
    hover_name='State',
    scope='usa',
    color_continuous_scale='Blues',
    labels={
        selected_column: 'Degrees Awarded'
    },
    title='Degrees Awarded by State (2023-2024)'
)

fig.update_layout(
    width=1000,
    height=600,
    geo=dict(bgcolor='rgba(0,0,0,0)')
)

fig.show()

**Table 4**

**Table 5**

In [49]:
import plotly.express as px

# Using cipcode_totals_with_description as it already contains the aggregated 'Total Count' for each CIPCODE
# Sort the data for better visualization, showing larger segments first
treemap_data = cipcode_totals_with_description.sort_values(by='Total Count', ascending=False)

fig = px.treemap(
    treemap_data,
    path=[px.Constant("All Degrees"), 'Description'], # Creates a hierarchy 'All Degrees' -> 'Description'
    values='Total Count',
    title='Overall Distribution of Degrees by Major',
    color='Total Count', # Color by Total Count
    color_continuous_scale='Blues', # Use a blue color scale
    hover_data=['CIPCODE', 'Total Count'] # Show CIPCODE and Total Count on hover
)

fig.update_layout(margin = dict(t=50, l=25, r=25, b=25))
fig.show()

In [50]:
import pandas as pd
import altair as alt

# Calculate growth for each description
growth_data = []

for desc in degrees_growth_data['Description'].unique():
    subset = degrees_growth_data[degrees_growth_data['Description'] == desc].sort_values('YEAR')

    if len(subset) > 1:
        first_year_data = subset.iloc[0]
        last_year_data = subset.iloc[-1]

        initial_degrees = first_year_data['Degrees_Awarded']
        final_degrees = last_year_data['Degrees_Awarded']
        initial_year = first_year_data['YEAR']
        final_year = last_year_data['YEAR']

        # Avoid division by zero for growth calculation
        if initial_degrees > 0:
            growth_percent = ((final_degrees - initial_degrees) / initial_degrees) * 100
            growth_data.append({
                'Description': desc,
                'Initial_Degrees': initial_degrees,
                'Final_Degrees': final_degrees,
                'Initial_Year': initial_year,
                'Final_Year': final_year,
                'Growth_Percent': growth_percent,
                'Years_Span': final_year - initial_year
            })
        elif final_degrees > 0: # If started at 0 but grew
            growth_data.append({
                'Description': desc,
                'Initial_Degrees': initial_degrees,
                'Final_Degrees': final_degrees,
                'Initial_Year': initial_year,
                'Final_Year': final_year,
                'Growth_Percent': float('inf'), # Represent as infinite growth
                'Years_Span': final_year - initial_year
            })

growth_df = pd.DataFrame(growth_data)

# Sort by growth percent to find the fastest growing
growth_df_sorted = growth_df.sort_values(by='Growth_Percent', ascending=False)

# Display the top 10 fastest growing fields
print("Top 10 Fastest Growing Fields:")
display(growth_df_sorted.head(10))

# Identify the fastest growing field
if not growth_df_sorted.empty:
    fastest_growing_field = growth_df_sorted.iloc[0]
    print(f"\nThe fastest growing field is: {fastest_growing_field['Description']} "
          f"with a growth of {fastest_growing_field['Growth_Percent']:.2f}% "
          f"(from {fastest_growing_field['Initial_Degrees']} degrees in {fastest_growing_field['Initial_Year']} "
          f"to {fastest_growing_field['Final_Degrees']} degrees in {fastest_growing_field['Final_Year']}).")
else:
    print("No growth data available.")


# Visualize the growth rates
# Filter out infinite growth for a meaningful bar chart, or handle it specially
chart_data = growth_df_sorted[growth_df_sorted['Growth_Percent'] != float('inf')].head(20)

bar_chart = alt.Chart(chart_data).mark_bar().encode(
    x=alt.X('Growth_Percent:Q', title='Percentage Growth (from initial to final year)'),
    y=alt.Y('Description:N', sort='-x', title='Field Description'),
    tooltip=[
        'Description:N',
        'Initial_Degrees:Q',
        'Final_Degrees:Q',
        'Initial_Year:O',
        'Final_Year:O',
        alt.Tooltip('Growth_Percent:Q', format='.2f', title='Growth %')
    ]
).properties(
    title='Top 20 Fields by Percentage Growth (from first to last recorded year)'
).interactive()

bar_chart

Top 10 Fastest Growing Fields:

,Description,Initial_Degrees,Final_Degrees,Initial_Year,Final_Year,Growth_Percent,Years_Span
91,Artificial Intelligence and Robotics,2,32,2010,2024,1500.000000,14
78,Surveying Engineering,2,12,2005,2024,500.000000,19
68,Computer and Information Systems Security,68,371,2005,2024,445.588235,19
11,Biomedical/Medical Engineering,48,211,2000,2024,339.583333,24
71,Computer Software Engineering,28,118,2005,2024,321.428571,19
58,"Computer and Information Sciences, Other",17,69,2005,2024,305.882353,19
66,System Administration/Administrator,12,41,2005,2024,241.666667,19
73,Construction Engineering,10,33,2005,2024,230.000000,19
43,Biomedical Technology/Technician,4,13,2000,2024,225.000000,24
67,"System, Networking, and LAN/WAN Management/Man...",4,13,2005,2024,225.000000,19

The fastest growing field is: Artificial Intelligence and Robotics with a growth of 1500.00% (from 2 degrees in 2010 to 32 degrees in 2024).

alt.Chart(...)